### ISSUE TITLE
Not an issue, just asking how ready is your binding. 

### ISSUE THREAD

**Issue by EmTee70** [saiqi/monetdb-d#1]
I was trying to write it on my own, but it stopped at being able to call the first MonetDB functions from D. Thought of using MonetDB to store my Weblogs in a fast relational way and to be able to query for certain request statistics quite fast...

**Comment by saiqi** [comment]
So far, I've been able to invoke the MAPI functions I need from an other D app by using this binding, the MonetDB database was running locally though. It does the minimal job: writes & reads data and opens & closes connection. I did not deploy any production application having this driver as a dependency.

**Comment by EmTee70** [comment]
Thank you, I missed your answer in my (quite full) mailbox.
Would be nice to have a README,  just pointing to your unittest would be useful.
